/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
export function DuckModel(props) {
  const { nodes, materials } = useGLTF('/models/duck.glb')
  const newMaterial = new THREE.MeshNormalMaterial()
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.character_duck.geometry}
        // material={materials['White.026']}
        material={newMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.character_duckArmLeft.geometry}
          // material={materials['White.026']}
          material={newMaterial}
          position={[0.204, 0, -0.634]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.character_duckArmRight.geometry}
          // material={materials['White.026']}
          material={newMaterial}
          position={[-0.204, 0, -0.634]}
        />
        <group position={[0, 0, -0.704]}>
          <mesh castShadow receiveShadow geometry={nodes.Cube1338.geometry} material={materials['White.026']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube1338_1.geometry} material={materials['Yellow.043']} />
          <mesh castShadow receiveShadow geometry={nodes.Cube1338_2.geometry} material={materials['Black.027']} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/duck.glb')
