/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Firdaus Sahak (https://sketchfab.com/firdaussahak)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/witch-house-4896881d43054ca3b4288b4085f482be
title: Witch House
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Home(props) {
  const { nodes, materials } = useGLTF("/models/witch_house.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[23.28, 50.62, -8.74]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Clock_MAT}
            />
          </group>

          {/* body of tower */}
          <group position={[22.13, 40.73, -13.93]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.DoorFrame_MAT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.MidFrame_MAT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.HouseBase_MAT}
            />
          </group>

          <group position={[22.86, 78.16, -17.25]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Roof_MAT}
            />
          </group>
          <group position={[26.12, 46.63, -8.01]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.WindowFrame_MAT}
            />
          </group>

          <group position={[27.45, 76.7, -34.37]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.GreenMetal_MAT}
            />
          </group>
          <group position={[40.64, 62.71, -7.85]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.DrainSupport_MAT}
            />
          </group>
          <group position={[21.51, 17.08, -16.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.MidFrame_MAT}
            />
          </group>
          <group position={[22.37, 29.44, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.SideFrame_MAT}
            />
          </group>
          <group position={[9.4, 53.87, -17.23]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.LWindow_MAT}
            />
          </group>

          <group position={[23.64, 50.41, -26.38]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Backdoor_MAT}
            />
          </group>
          <group position={[22, 20.74, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.CrossPlank_MAT}
            />
          </group>
          <group position={[23.83, 63.66, -6.82]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.CuckooBase_MAT}
            />
          </group>
          <group position={[14.77, 41.4, -8.44]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[30.95, 40.71, -8.44]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[32.58, 58.85, -7.6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[22.79, 66.55, -7.47]}>
            <group position={[0.68, -0.18, 0.25]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.Knob_MAT}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.Red_MAT}
            />
          </group>
          <group position={[25.1, 66.45, -7.47]}>
            <group position={[-0.69, -0.13, 0.25]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.Knob_MAT}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.Red_MAT}
            />
          </group>
          <group position={[36.33, 74.48, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.VentFrame_MAT}
            />
          </group>
          <group position={[35.65, 73.44, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.VentRoof_MAT}
            />
          </group>
          <group position={[15.96, 75.49, -17.31]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.RoofWindow_MAT}
            />
          </group>
          <group position={[16.03, 75.43, -17.31]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[37.71, 53.8, -17.25]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[37.83, 53.3, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials.RWindow_MAT}
            />
          </group>
          <group position={[23.96, 13.53, -7.98]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.Knob_MAT}
            />
          </group>
          <group position={[23.94, 13.43, -8.53]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.GoldMetal_MAT}
            />
          </group>
          <group position={[18.4, 13.75, -8.81]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.GoldMetal_MAT}
            />
          </group>
          <group position={[21.61, 14.79, -8.76]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.Door_MAT}
            />
          </group>
          <group position={[21.58, 13.58, -8.6]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.DoorPlank_MAT}
            />
          </group>
          <group position={[38.96, 36.98, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials.RedMetal_MAT}
            />
          </group>
          <group position={[35.47, 30.32, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.RedMetal_MAT}
            />
          </group>
          <group position={[42.83, 64.64, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials.Drain_MAT}
            />
          </group>
          <group position={[14.97, 20.76, -7.67]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials.GreenMetal_MAT}
            />
          </group>
          <group position={[15.01, 21.83, -8.31]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_74.geometry}
              material={materials.GreenMetal_MAT}
            />
          </group>
          <group position={[14.89, 19, -7.67]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_76.geometry}
              material={materials.Glass_MAT}
            />
          </group>
          <group position={[14.88, 18.75, -7.67]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_78.geometry}
              material={materials.RedMetal_MAT}
            />
          </group>
          <group position={[3.85, 61.1, -17.23]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_80.geometry}
              material={materials.Curtain_MAT}
            />
          </group>
          <group position={[3.39, 60.82, -17.23]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_82.geometry}
              material={materials.String_MAT}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_83.geometry}
              material={materials.CurtainPlank_MAT}
            />
          </group>
          <group position={[5.84, 52.73, -3.89]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_85.geometry}
              material={materials.String_MAT}
            />
          </group>
          <group position={[5.64, 47.98, -3.87]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_87.geometry}
              material={materials.Star_MAT}
            />
          </group>
          <group position={[23.25, 50.26, -8.42]}>
            <group position={[0.17, 3.89, -0.03]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_91.geometry}
                material={materials.GreenMetal_MAT}
              />
            </group>
            <group position={[2.47, -1.7, -0.35]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_93.geometry}
                material={materials.GreenMetal_MAT}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.GreenMetal_MAT}
            />
          </group>
          <group position={[-13.35, 35.34, -26.1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.Nail_MAT}
            />
          </group>
          <group position={[-13.45, 36.76, -26.27]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_97.geometry}
              material={materials.StairsPillar_MAT}
            />
          </group>
          <group position={[-23.34, 19.98, -30.18]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials.StairsBase_MAT}
            />
          </group>
          <group position={[-21.09, 5.89, -44.5]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_101.geometry}
              material={materials.StairsLv3_MAT}
            />
          </group>
          <group position={[-26.54, 19.04, -30.65]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_103.geometry}
              material={materials.StairsLv2_MAT}
            />
          </group>
          <group position={[-11.78, 37.16, -17.23]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_105.geometry}
              material={materials.StairsLv1_MAT}
            />
          </group>
          <group position={[-26.27, 18.11, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_107.geometry}
              material={materials.StairsFloor_MAT}
            />
          </group>
          <group position={[-27.07, 6.6, -44.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_109.geometry}
              material={materials.StairsFloor_MAT}
            />
          </group>
          <group position={[-14.06, 1.85, -44.5]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials.StairsFloor_MAT}
            />
          </group>
          <group position={[3.48, 46.87, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_113.geometry}
              material={materials.StairsTop_MAT}
            />
          </group>
          <group position={[-21.27, 28.95, -29.95]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_115.geometry}
              material={materials.HandrailIn2_MAT}
            />
          </group>
          <group position={[-10.2, 47.69, -22.06]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_117.geometry}
              material={materials.HandrailIn1_MAT}
            />
          </group>
          <group position={[-26.66, 27.63, -33.37]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_119.geometry}
              material={materials.HandrailOut_MAT}
            />
          </group>
          <group position={[10.29, 11.57, -33.8]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_121.geometry}
              material={materials.BackWallDoor_MAT}
            />
          </group>
          <group position={[20.06, 14.73, -36.2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_123.geometry}
              material={materials.BackWall_MAT}
            />
          </group>
          <group position={[21.88, 18.19, -43.17]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_125.geometry}
              material={materials.WoodPath_MAT}
            />
          </group>
          <group position={[21.92, 19.07, -43.38]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_127.geometry}
              material={materials.GrayMetal_MAT}
            />
          </group>
          <group position={[21.91, 18.81, -43.94]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_129.geometry}
              material={materials.Bolt_MAT}
            />
          </group>
          <group position={[21.47, 8.3, -3.26]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_131.geometry}
              material={materials.Nail_MAT}
            />
          </group>
          <group position={[21.47, 8.4, -3.26]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_133.geometry}
              material={materials.FrontHandrail_MAT}
            />
          </group>
          <group position={[21.85, 4.2, -0.64]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_135.geometry}
              material={materials.FrontStairs_MAT}
            />
          </group>
          <group position={[26.32, 14.45, -31.62]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_137.geometry}
              material={materials.GrayMetal_MAT}
            />
          </group>
          <group position={[26.7, 17.29, -31.38]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_139.geometry}
              material={materials.Bolt_MAT}
            />
          </group>
          <group position={[26.44, 17.27, -31.34]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_141.geometry}
              material={materials.GrayMetal_MAT}
            />
          </group>
          <group position={[21.16, 5.24, -17.23]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_143.geometry}
              material={materials.Floorboard_MAT}
            />
          </group>
          <group position={[21.24, 3.09, -17.24]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_145.geometry}
              material={materials.FloorSupport_MAT}
            />
          </group>
          <group position={[19.35, 1.11, 21.16]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_147.geometry}
              material={materials.StoneS_MAT}
            />
          </group>
          <group position={[21.69, 1.02, 17.67]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_149.geometry}
              material={materials.StoneL_MAT}
            />
          </group>
          <group position={[21.55, 1, 17.46]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_151.geometry}
              material={materials.StoneM_MAT}
            />
          </group>
          <group position={[21.09, -0.68, -79.53]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_153.geometry}
              material={materials.WoodPath_MAT}
            />
          </group>
          <group position={[21.14, 0.1, -79.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_155.geometry}
              material={materials.GrayMetal_MAT}
            />
          </group>
          <group position={[21.14, 0.01, -79.56]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_157.geometry}
              material={materials.lambert1}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/witch_house.glb");
export default Home;
