/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import {useGLTF} from "@react-three/drei";
import {GroupProps} from "@react-three/fiber";

export function StylizedAirPlane(props: GroupProps) {
  const {nodes, materials} = useGLTF("/models/stylized_airplane.glb");

  return (
    <group
      rotation-x={-Math.PI / 2}
      rotation-z={(Math.PI * 3) / 4}
      scale={[0.002, 0.002, 0.002]}
      dispose={null}
      {...props}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Stylized_EarlyRumplerIV_Material_#25_0"].geometry}
        material={materials.Material_25}
      />
    </group>
  );
}

useGLTF.preload("/models/stylized_airplane.glb");
